---
- hosts: all
  sudo: true

  vars:
    app_dir: '/srv/apps/hires'
    app_secret: 'bb255856ab9d8e1061b03060489bd96c4504c5ca2010d8507447355b72ec55e6fdf00524ad60e8ea47d974d978bce221b451e6bbafcf5baddb2b33e59b359a9a'

  tasks:
    - name: app | git
      apt: pkg=git-core
           update-cache=yes
           state=latest

    - name: app | shared dirs
      file: path={{ app_dir }}/shared/{{ item }}
            state=directory
      with_items:
        - config
        - log
        - public/system
        - tmp/cache
        - tmp/pids
        - tmp/sockets
        - vendor/bundle

    - name: app | database.yaml
      copy: src=files/database.yml
            dest={{ app_dir }}/shared/config/database.yml

    - name: app | modes
      shell: chmod 755 -R {{ app_dir }}

    - name: app | owners
      shell: chown deploy:deploy -R {{ app_dir }}

    - name: app | app secret env var
      lineinfile: dest=/home/deploy/.profile
                  regexp="^export APP_SECRET"
                  line="export APP_SECRET={{ app_secret }}"
                  state=present
