---
- hosts: all
  sudo: true

  tasks:
    - name: app | git
      apt: pkg=git-core
           update-cache=yes
           state=latest

    - name: app | shared dirs
      file: path={{ app_dir }}/shared/{{ item }}
            state=directory
      with_items:
        - config
        - log
        - public/system
        - tmp/cache
        - tmp/pids
        - tmp/sockets
        - vendor/bundle

    - name: app | database.yaml
      copy: src=files/database.yml
            dest={{ app_dir }}/shared/config/database.yml

    - name: app | modes
      shell: chmod 755 -R {{ app_dir }}

    - name: app | owners
      shell: chown deploy:deploy -R {{ app_dir }}

    - name: app | unicorn init
      template: src=files/unicorn.sh
                dest=/etc/init.d/unicorn
                owner=root
                group=root
                mode=655

    - name: app | unicorn conf dir
      file: dest=/etc/unicorn
            owner=root
            group=root
            mode=655
            state=directory

    - name: app | unicorn conf file
      template: src=templates/unicorn.conf.j2
                dest=/etc/unicorn/rails.conf
                owner=root
                group=root
                mode=644
