---
- hosts: all
  sudo: true

  vars:
    nginx_tarball_url: http://nginx.org/download/nginx-1.4.7.tar.gz
    nginx_tarball_sha256sum: 23b8ff4a76817090678f91b0efbfcef59a93492f6612dc8370c44c1f1ce1b626
    nginx_version: 1.4.7

  tasks:
    - name: nginx | build dependencies
      apt: pkg={{ item }}
           state=latest
           update-cache=yes
      with_items:
        - build-essential
        - libpcre3-dev
        - libssl-dev

    - name: nginx | download tarball
      get_url: url={{ nginx_tarball_url }}
               dest=/usr/local/src/nginx-{{ nginx_version }}.tar.gz
               sha256sum={{ nginx_tarball_sha256sum }}

    - name: nginx | extract tarball
      command: tar -zxf nginx-{{ nginx_version }}.tar.gz
               chdir=/usr/local/src
               creates=/usr/local/src/nginx-{{ nginx_version }}

    - name: nginx | configure
      command: ./configure --prefix=/opt/nginx-{{ nginx_version }} --conf-path=/etc/nginx/nginx.conf --pid-path=/run/nginx.pid --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --with-http_ssl_module
               chdir=/usr/local/src/nginx-{{ nginx_version }}
               creates=/usr/local/src/nginx-{{ nginx_version }}/Makefile

    - name: nginx | make
      command: make
               chdir=/usr/local/src/nginx-{{ nginx_version }}
               creates=/usr/local/src/nginx-{{ nginx_version }}/nginx

    - name: nginx | make install
      command: make install
               chdir=/usr/local/src/nginx-{{ nginx_version }}
               creates=/opt/nginx-{{ nginx_version }}

    - name: nginx | unprivileged group
      group: name=nginx
             state=present

    - name: nginx | unprivileged user
      user: name=nginx
            group=nginx
            createhome=no
            state=present

    - name: nginx | copy nginx init script
      template: src=templates/nginx.init.j2
                dest=/etc/init.d/nginx
                mode=0655
                owner=root
                group=root

    - name: nginx | copy nginx conf
      template: src=templates/nginx.conf.j2
                dest=/etc/nginx/nginx.conf
                mode=0644
                owner=root
                group=root
      notify: restart nginx

    - name: nginx | start on boot
      service: name=nginx
               enabled=yes

  handlers:
    - name: restart nginx
      service: name=nginx
               state=restarted
