---
- hosts: all
  sudo: true

  tasks:
    - name: postgres | install dependencies
      apt: pkg={{ item }}
           update-cache=yes
           state=latest
      with_items:
        - python-pycurl
        - python-psycopg2

    - name: postgres | repository
      apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'
                      state=present

    - name: postgres | key
      apt_key: id=ACCC4CF8
               url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
               state=present

    - name: postgres | install
      apt: pkg={{ item }}
           state=latest
           update-cache=yes
      with_items:
        - postgresql-9.3
        - postgresql-server-dev-9.3

- hosts: all
  sudo: true
  sudo_user: postgres

  tasks:
    - name: postgres | database
      postgresql_db: name={{ postgres_database }}
                     state=present

    - name: postgres | role
      postgresql_user: name={{ postgres_username }}
                       state=present

    - name: postgres | privileges
      postgresql_privs: database={{ postgres_database }}
                        privs=ALL
                        type=database
                        role={{ postgres_username }}
                        state=present
