---
- hosts: all
  sudo: true

  tasks:
    - name: ufw | deny incoming
      shell: ufw default deny incoming

    - name: ufw | allow outgoing
      shell: ufw default allow outgoing

    - name: ufw | allow in ssh
      shell: ufw allow in ssh

    - name: ufw | allow in http
      shell: ufw allow in http

    - name: ufw | enable
      shell: echo 'y' | ufw enable
