---
- hosts: all
  sudo: true

  vars_prompt:
    - name: devop_ssh_public_key_path
      prompt: "SSH public key path for devop user"
      default: ~/.ssh/id_rsa.pub

    - name: deploy_ssh_public_key_path
      prompt: "SSH public key path for deploy user"
      default: ~/.ssh/id_rsa.pub

  tasks:
    - name: users | ssh group
      group: name=ssh
             state=present

    - name: users | devop group
      group: name=devop
             state=present

    - name: users | devop generate random password
      shell: openssl rand -base64 24
      register: devop_password

    - name: users | devop user
      user: name=devop
            group=devop
            groups=admin,ssh
            password={{ devop_password.stdout }}
            shell=/bin/bash
            state=present

    - name: users | devop authorized key
      authorized_key: user=devop
                      key="{{ lookup('file', devop_ssh_public_key_path) }}"
                      state=present

    - name: users | deploy group
      group: name=deploy
             state=present

    - name: users | deploy generate random password
      shell: openssl rand -base64 24
      register: deploy_password

    - name: users | deploy user
      user: name=deploy
            group=deploy
            groups=ssh
            password={{ deploy_password.stdout }}
            shell=/bin/bash
            state=present

    - name: users | deploy authorized key
      authorized_key: user=deploy
                      key="{{ lookup('file', deploy_ssh_public_key_path) }}"
                      state=present

    - name: users | sshd config
      copy: src=files/sshd_config
            dest=/etc/ssh/sshd_config
      notify:
        - restart ssh

  handlers:
    - name: restart ssh
      service: name=ssh state=restarted
