---
- hosts: all
  sudo: true

  vars_prompt:
    - name: deploy_ssh_public_key_path
      prompt: "SSH public key path for deploy user"
      default: ~/.ssh/id_rsa.pub

  tasks:
    - name: deploy | deploy group
      group: name={{ deploy_username }}
             state=present

    - name: deploy | generate random password
      shell: openssl rand -base64 24
      register: deploy_password

    - name: deploy | deploy user
      user: name=deploy
            group={{ deploy_username }}
            groups=ssh
            password={{ deploy_password.stdout }}
            shell=/bin/bash
            state=present

    - name: deploy | deploy sudoer
      copy: src=files/sudoers
            dest=/etc/sudoers.d/{{ deploy_username }}
            owner=root
            group=root
            mode=440

    - name: deploy | deploy authorized key
      authorized_key: user={{ deploy_username }}
                      key="{{ lookup('file', deploy_ssh_public_key_path) }}"
                      state=present

    - name: deploy | git
      apt: pkg=git-core
           update-cache=yes
           state=latest

    - name: deploy | app dir
      file: path={{ deploy_app_dir }}/shared/{{ item }}
            state=directory
      with_items:
        - config
        - log
        - public/system
        - tmp/cache
        - tmp/pids
        - tmp/sockets
        - vendor/bundle

    - name: deploy | app database.yaml
      copy: src=files/database.yml
            dest={{ deploy_app_dir }}/shared/config/database.yml

    - name: deploy | app permissions
    shell: chmod 755 -R {{ deploy_app_dir }}; chown {{ deploy_username }}:{{ deploy_username }} -R {{ deploy_app_dir }}

    - name: deploy | unicorn init
      template: src=files/unicorn.sh
                dest=/etc/init.d/unicorn
                owner=root
                group=root
                mode=655

    - name: deploy | unicorn conf dir
      file: dest=/etc/unicorn
            owner=root
            group=root
            mode=655
            state=directory

    - name: deploy | unicorn conf
      template: src=templates/unicorn.conf.j2
                dest=/etc/unicorn/rails.conf
                owner=root
                group=root
                mode=644

    - name: deploy | unicorn starts on boot
      service: name=unicorn
               enabled=yes

# TODO
# nodjs
# nginx sites available
# nginx sites enabled

- hosts: all
  sudo: true
  sudo_user: postgres

  tasks:
    - name: deploy | app database
      postgresql_db: name={{ postgres_database }}
                     state=present

    - name: deploy | app role
      postgresql_user: name={{ postgres_username }}
                       state=present

    - name: deploy | app privileges
      postgresql_privs: database={{ postgres_database }}
                        privs=ALL
                        type=database
                        role={{ postgres_username }}
                        state=present
