---
- hosts: all
  sudo: true

  tasks:
    - name: dotenv | env
      template: src=templates/dotenv.j2
                dest={{ deploy_app_dir }}/shared/.env
                owner={{ deploy_username }}
                group={{ deploy_username }}
                mode=644
